import type { Metadata } from "next";
import "./styles/globals.css";
import { NavLinkProps } from "./components/layout/navbar";
import Header from "./components/layout/header";
import Hero from "./components/layout/hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links: NavLinkProps[] = [
    { name: 'Home', href: '/' },
    { name: 'About', href: '/about'  },
    { name: 'Projects', href: '/projects'  },
    { name: 'Gallery', href: '/gallery'  },
    { name: 'Blog', href: '/blog'  },
    { name: 'Contact', href: '/contact'  },
  ];
  return (
    <html lang="en">
      <body>
        <div className={`body_page_`}>
          <Header navLinks={links}></Header>
          <Hero title={metadata.title} subTitle={"Welcome to our web site, we gonna do our best to help you out"}></Hero>
          
          <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
            {children}
          </main>
          
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
        </div>
      </body>
    </html>
  );
}
